name: Build, Test, and Publish Healthwise.Sdo.Events

on:
  push:
    branches: [main]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      #- name: Configure NuGet sources
      #  run: |
      #    dotnet nuget add source https://nuget.pkg.github.com/mprice-hw/index.json -n "mprice-hw GitHub Packages" -u ${{ secrets.BUILD_SYSTEM_LOGIN }} --store-password-in-clear-text -p ${{ secrets.BUILD_SYSTEM_PAT }}
      #  env:
      #    BUILD_SYSTEM_LOGIN: ${{ secrets.BUILD_SYSTEM_LOGIN }}
      #    BUILD_SYSTEM_PAT: ${{ secrets.BUILD_SYSTEM_PAT }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Healthwise.Sdo.Events
        run: |
          echo ${GITHUB_RUN_NUMBER}
          dotnet build --no-restore --configuration Release -p:buildnumber=${GITHUB_RUN_NUMBER}

      #- name: Test Healthwise.BackEndEvents
      #  run: dotnet test --no-build --configuration Release -p:buildnumber=${GITHUB_RUN_NUMBER} --verbosity normal

      - name: Create Nuget Package
        run: dotnet pack --configuration Release -p:buildnumber=${GITHUB_RUN_NUMBER} --output .

      - name: Publish Healthwise.Sdo.Events to GitHub Packages
        run: dotnet nuget push "./*.nupkg" -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/mprice-hw/index.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
